replicaCount: 3

image:
  tag: "0.0.4"
  pullPolicy: IfNotPresent

resources:
  requests:
    cpu: 500m
    memory: 768Mi
  limits:
    cpu: 2000m
    memory: 1Gi

autoscaling:
  enabled: true
  minReplicas: 3
  maxReplicas: 8
  targetCPUUtilizationPercentage: 70

podAnnotations:
  cluster-autoscaler.kubernetes.io/safe-to-evict: "false"

env:
  - name: SPRING_PROFILES_ACTIVE
    value: prod
