replicaCount: 2

image:
  tag: "0.0.1"
  pullPolicy: IfNotPresent

resources:
  requests:
    cpu: 500m
    memory: 768Mi
  limits:
    cpu: 1500m
    memory: 1Gi

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 6
  targetCPUUtilizationPercentage: 70

podAnnotations:
  cluster-autoscaler.kubernetes.io/safe-to-evict: "true"

env:
  - name: SPRING_PROFILES_ACTIVE
    value: prod
