replicaCount: 2

image:
  tag: "qa"
  pullPolicy: IfNotPresent

resources:
  requests:
    cpu: 250m
    memory: 512Mi
  limits:
    cpu: 1000m
    memory: 768Mi

autoscaling:
  enabled: false

env:
  - name: SPRING_PROFILES_ACTIVE
    value: qa
