spring:
  application:
    name: processing-service

  config:
    import: optional:configserver:http://configserver:8888

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: