spring.application.name=aggregation-service
spring.config.import=optional:configserver:http://${CONFIG_SERVER_USER}:${CONFIG_SERVER_PASSWORD}@configserver:8888

#---
spring.config.activate.on-profile=local
spring.cloud.vault.enabled=false

#---
spring.config.activate.on-profile=!local
spring.config.import=vault://
spring.cloud.vault.host=vault
spring.cloud.vault.port=8200
spring.cloud.vault.scheme=http
spring.cloud.vault.authentication=APPROLE
spring.cloud.vault.app-role.role-id=${VAULT_ROLE_ID}
spring.cloud.vault.app-role.secret-id=${VAULT_SECRET_ID}
spring.cloud.vault.database.enabled=true
spring.cloud.vault.database.role=aggregation-service-db
spring.cloud.vault.database.username-property=spring.datasource.username
spring.cloud.vault.database.password-property=spring.datasource.password
