spring:
  application:
    name: ingestion-service

  config:
    import:
      - optional:configserver:http://${CONFIG_SERVER_USER}:${CONFIG_SERVER_PASSWORD}@configserver:8888
      - vault://

  cloud:
    vault:
      host: vault
      port: 8200
      scheme: http
      authentication: APPROLE
      app-role:
        role-id: ${VAULT_ROLE_ID}
        secret-id: ${VAULT_SECRET_ID}
      database:
        enabled: true
        role: ingestion-service-db
        username-property: spring.datasource.username
        password-property: spring.datasource.password
