replicaCount: 3

image:
  tag: "0.0.1"
  pullPolicy: IfNotPresent

resources:
  requests:
    cpu: 500m
    memory: 768Mi
  limits:
    cpu: 2000m
    memory: 1Gi

autoscaling:
  enabled: true
  minReplicas: 3
  maxReplicas: 10
  targetCPUUtilizationPercentage: 65

podAnnotations:
  cluster-autoscaler.kubernetes.io/safe-to-evict: "false"

ingress:
  enabled: true
  className: nginx
  host: api.financial-platform.example.com
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
  tls:
    - hosts:
        - api.financial-platform.example.com
      secretName: api-gateway-tls

env:
  - name: SPRING_PROFILES_ACTIVE
    value: prod
